version: '3.18'
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database-dev-6
    ports:
      - "5442:5432"
    volumes:
      - postgres_data_dev_6:/var/lib/postgresql/data
    networks:
      - postgres_network_dev_6

  pgadmin:
    image: dpage/pgadmin4:8.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres_network_dev_6

networks:
  postgres_network_dev_6:
    driver: bridge

volumes:
  postgres_data_dev_6:
